### ISSUE TITLE
Update to latest version / make versionless?

### ISSUE THREAD

**Issue by NelsonMinar** [nubing/factorio-headless#1]
Thanks for doing the work to make this Snap! I got it working but I had to update the Factorio version in snapcraft.yaml (in the obvious way) and rebuild the Snap. I imagine that's tedious work you're not interested in doing regularly. But you own the name on the Snap store; any idea how to keep that publically published version working?

The ideal thing would be if I could just say `snap install factorio-headless --experimental` and it magically find the latest experimental version for me. I'd be glad to hack up a shell script that produces the current stable and experimental version strings, if you wanted to incorporate it somehow into the Snap build process. I don't know anything about Snap builds myself so can't do the full thing.

**Comment by nubing** [comment]
Yeah, I'm trying to figure out how to trigger builds when they publish new versions. Parsing current version from site is not the problem, knowing exactly when to build is the issue because clients and server must be same version or they'll refuse to connect.

Updated to 0.17.79 on stable and beta channels. Use beta channel for "experimental" so do `snap install factorio-headless --beta`.

**Comment by nubing** [comment]
Setup notification system for new releases and keeping up to date now.
https://factorio.com/api/latest-releases
